### ISSUE TITLE
Sensors are not showing up under integration

### ISSUE THREAD

**Issue by foosel** [foosel/homeassistant-coronavirus-hessen#3]
As mentioned in the README, the sensors are currently not showing up in the integration. The bundled international coronavirus component however has them show up just fine:

![image](https://user-images.githubusercontent.com/83657/76846646-1d2ef100-6841-11ea-811a-6dbbdd0f5c06.png)

This should be fixed, though I currently have no idea where to even start looking. Any help is appreciated.

**Comment by mklik** [comment]
Hi Gina,
I have really no experiance in writing integrations for home assistant but I'm pretty shure that each sensor has to have a uniqe ID.
This seems to me as the main cause of many issues. But don't ask me how to create such an ID.
Hope this helps and thanks for your effort.

**Comment by foosel** [comment]
That helped indeed :)
