### ISSUE TITLE
Feature Request: other federal states / Sensor "new since yesterday"

### ISSUE THREAD

**Issue by Pe-MaKer** [foosel/homeassistant-coronavirus-hessen#6]
Dear Foosel,
thanks for this custom component.
The numbers from the city or county are better suited for integration into the smart home than the national or global numbers.
Unfortunately I need another data source, because I do not live in beautiful Hessen.

Would it be feasible for you to modify your scraper and display other federal states?

It would be ideal, if a new sensor for the " Fälle - Änderung zum Vortag" would be added. At least the Ministry of Health of Bavaria shows this separately (Table 4):
https://www.lgl.bayern.de/gesundheit/infektionsschutz/infektionskrankheiten_a_z/coronavirus/karte_coronavirus/index.htm#landkreise

**Comment by foosel** [comment]
I fear other states handle things too differently to keep this in one custom integration. But you are welcome to fork and adapt accordingly. I sadly lack the time as I already have a fairly [complex open source project to maintain](https://github.com/OctoPrint/OctoPrint), and that's also why I wouldn't accept a PR to merge this into this one (no time to maintain additional states).

**Comment by Pe-MaKer** [comment]
My development skills are in a rusted state since 2003. Not even "hobby grade" anymore.

I really appreciate your work on OctoPrint, which I also use myself. It is clear that such side projects as the HA integration cannot be extended indefinitely.

Thanks and many greetings from Franconia.
